version: '3'
 
services:
  nginx:
    build:
      context: .
      dockerfile: conf/Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - simu
  simu:
    build:
      context: .
      dockerfile: conf/Dockerfile.simu
    restart: unless-stopped
    volumes:
      - "./simulator/log:/online_simulator/log"
      - "./simulator/upload:/online_simulator/upload"

