version: '3'
 
services:
  nginx:
    build:
      context: .
      dockerfile: conf/Dockerfile.nginx
    deploy:
      restart_policy: 
        condition: on-failure
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - simu
  simu:
    build:
      context: .
      dockerfile: conf/Dockerfile.simu
    deploy:
      restart_policy: 
        condition: on-failure
    restart: unless-stopped
    volumes:
      - "/srv/risc16/log:/online_simulator/log"
      - "/srv/risc16/upload:/online_simulator/upload"

