FROM debian:stretch

EXPOSE 8000

COPY online_simulator online_simulator

WORKDIR online_simulator

RUN apt-get update && apt-get install -y \
    git \
    python-pip \
    python-flask \
    python-matplotlib \
    gunicorn

CMD gunicorn app_nginx:app -b 0.0.0.0:8000
